/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  prefix: '',
  safelist: ['rounded-5', 'rounded-6', 'rounded-7', 'rounded-8', 'rounded-9', 'rounded-10', 'rounded-11', 'rounded-12'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        sm: '120rem',
        md: '120rem',
        lg: '120rem',
        xl: '120rem',
        '2xl': '120rem',
      },
    },
    extend: {
      screens: {
        xs: '24rem',
      },
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        'elements-border-primary': 'var(--primitives-stone-gray-300)',
        'elements-border-secondary': 'var(--primitives-stone-gray-200)',
        'elements-border-tertiary': 'var(--primitives-stone-gray-100)',
        'elements-card': 'var(--primitives-base-white)',
        'elements-fg-card': 'var(--general-fg-primary)',
        'elements-fg-popover': 'var(--elements-fg-card)',
        'elements-input': 'var(--primitives-base-white)',
        'elements-popover': 'var(--elements-card)',
        'elements-ring': 'var(--general-brand-accent)',
        'general-brand-accent': 'var(--primitives-amber-brand-500)',
        'general-brand-subtle': 'var(--primitives-amber-brand-200)',
        'general-brand-hover': 'var(--primitives-amber-brand-700)',
        'general-fg-brand-accent': 'var(--primitives-base-white)',
        'general-fg-brand-subtle': 'var(--primitives-amber-brand-50)',
        'general-fg-inverse': 'var(--primitives-base-white)',
        'general-fg-inverse-subtle': 'var(--primitives-stone-gray-600)',
        'general-fg-primary': 'var(--primitives-stone-gray-900)',
        'general-fg-secondary': 'var(--primitives-stone-gray-600)',
        'general-fg-subtle': 'var(--primitives-stone-gray-300)',
        'general-fg-tertiary': 'var(--primitives-stone-gray-400)',
        'general-inverse': 'var(--primitives-stone-gray-900)',
        'general-inverse-hover': 'var(--primitives-stone-gray-700)',
        'general-primary': 'var(--primitives-stone-gray-50)',
        'general-secondary': 'var(--primitives-stone-gray-100)',
        'general-subtle': 'var(--primitives-stone-gray-100)',
        'general-tertiary': 'var(--primitives-stone-gray-200)',
        'utilities-destructive': 'var(--primitives-error-600)',
        'utilities-error': 'var(--primitives-error-500)',
        'utilities-error-hover': 'var(--primitives-error-700)',
        'utilities-fg-destructive': 'var(--primitives-base-white)',
        'utilities-fg-error': 'var(--primitives-error-50)',
        'utilities-fg-info': 'var(--primitives-base-white)',
        'utilities-fg-success': 'var(--primitives-success-50)',
        'utilities-fg-warning-primary': 'var(--primitives-amber-brand-50)',
        'utilities-info': 'var(--general-fg-primary)',
        'utilities-success': 'var(--primitives-success-500)',
        'utilities-warning': 'var(--primitives-amber-brand-600)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
        },
        error: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--error-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
      },
      borderRadius: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        xl: 'calc(var(--radius) + 4px)',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--kb-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--kb-accordion-content-height)' },
          to: { height: 0 },
        },
        'content-show': {
          from: { opacity: 0, transform: 'scale(0.96)' },
          to: { opacity: 1, transform: 'scale(1)' },
        },
        'content-hide': {
          from: { opacity: 1, transform: 'scale(1)' },
          to: { opacity: 0, transform: 'scale(0.96)' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'content-show': 'content-show 0.2s ease-out',
        'content-hide': 'content-hide 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
}
